# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Build docker image as the CI environment"
description: "Build docker image as the CI environment from a given dockerfile"

inputs:
  imageTag:
    description: "Tag to apply to the docker image"
    required: false
    default: "rapidstream/tapa-buildenv:local"
  dockerfile:
    description: "Path to the dockerfile to build"
    required: false
    default: "./.github/docker/build-env/Dockerfile.binary"
  context:
    description: "Path to the build context"
    required: false
    default: "./.github/docker/build-env"

runs:
  using: "composite"
  steps:
    - name: Create docker image as the build environment
      run: >
        docker build \
          --pull \
          -t ${{ inputs.imageTag }} \
          -f ${{ inputs.dockerfile }} \
          --build-arg UBUNTU_PRO_TOKEN=${{ env.UBUNTU_PRO_TOKEN }} \
          --build-arg DOCKER_USER_ID=$(id -u) \
          --build-arg DOCKER_GROUP_ID=$(id -g) \
          ${{ inputs.context }}
      shell: bash
