# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Build the release distributions"
description: "Build the release distributions for the TAPA using Bazel"

runs:
  using: "composite"
  steps:
    - name: Run bazel for the software release
      uses: ./.github/actions/run-command
      with:
        run: |
          mkdir -p /workspace/artifacts.out/
          bazel build --config=release //:tapa-pkg-tar
          cp -L bazel-bin/tapa-pkg-tar.tar /workspace/artifacts.out/tapa.tar
          gzip /workspace/artifacts.out/tapa.tar

    - name: Run bazel for the visualizer release
      uses: ./.github/actions/run-command
      with:
        run: |
          bazel build --config=release //:tapa-visualizer-tar
          cp -L bazel-bin/tapa-visualizer-tar.tar /workspace/artifacts.out/tapa-visualizer.tar
          gzip /workspace/artifacts.out/tapa-visualizer.tar
        imageTag: rapidstream/tapa-visualizer-buildenv:local
        dockerfile: ./.github/docker/build-env/Dockerfile.visualizer
