# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: tapa/requirements_lock.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
