# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Run regression test"
description: "Run and report the frequency results of a given design"

inputs:
  test:
    description: "Test to run"
    required: true
  os:
    description: "Operating system to run the test"
    default: "ubuntu-20"
  vivado:
    description: "Vivado version to run the test"
    default: "2023.2"
  tapaVersion:
    description: "TAPA version to run the test"
    default: "latest"
  rapidstreamVersion:
    description: "RapidStream version to run the test"
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Setup and run the test
      uses: ./.github/actions/run-command
      with:
        run: |
          curl -fsSL tapa.rapidstream.sh > /tmp/tapa.sh
          sh /tmp/tapa.sh --version ${{ inputs.tapaVersion }} -q
          curl -fsSL rapidstream.sh > /tmp/rapidstream.sh
          sh /tmp/rapidstream.sh --version ${{ inputs.rapidstreamVersion }} -q
          export PATH=~/.rapidstream-tapa/usr/bin:~/.rapidstream:$PATH
          export TAPA_CONCURRENCY=1
          source /opt/tools/xilinx/Vitis/${{ inputs.vivado }}/settings64.sh
          cd tests/regression/${{ inputs.test }}/rapidstream
          bash run_rs.sh
        image: rapidstream/tapa-testenv:${{ inputs.os }}
        dockerfile: ./.github/docker/regression-env/Dockerfile.${{ inputs.os }}
        context: ./.github/docker/regression-env
