# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: Frequency Regression

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: regression
  cancel-in-progress: false

jobs:
  frequency-regression:
    name: Run Frequency Regression
    runs-on: self-hosted

    # seven days for the regression jobs
    timeout-minutes: 10080

    strategy:
      # run all tests even if one fails
      fail-fast: false
      matrix:
        test:
          - autosa/mm/10x13/u250
          - autosa/mm/10x13/u55c
          - callipepla
          - serpens-32ch
          - spmm/sextans-u55c-3x3floorplan
      max-parallel: 2

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4

      - name: Run frequency regression on the given test
        uses: ./.github/actions/run-regression
        with:
          test: ${{ matrix.test }}
          os: ubuntu-22
          vivado: "2023.2"
          tapaVersion: "latest"
          rapidstreamVersion: "latest"
