# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: Build and Publish Stable Version

concurrency:
  group: release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Release:
    runs-on: self-hosted
    environment: release

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4

      - name: Build the distributions
        uses: ./.github/actions/build-release
        env:
          UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
          MAC_ADDRESS: ${{ secrets.MAC_ADDRESS }}

      - name: Publish the distributions
        uses: ./.github/actions/publish-dist
        with:
          channel: stable
          cloudflareToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Checkout rapidstream-da/rapidstream
        uses: actions/checkout@v4
        with:
          path: rapidstream
          ref: main
          repository: rapidstream-da/rapidstream
          token: ${{ secrets.GH_RAPIDSTREAM_PAT }}

      - name: Bump TAPA version in RapidStream
        run: |
          cd rapidstream
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b ci-bump-tapa-version/next
          sed -i "s/--version=.* /--version=$(cat ../VERSION) /" buildutils/Dockerfile.ci-env
          git add buildutils/Dockerfile.ci-env
          git commit -m "ci: bump TAPA version to $(cat ../VERSION)"
          git push --force origin ci-bump-tapa-version/next
